### ISSUE TITLE
trouble running app - mongoskin/lib/utils.js:33

### ISSUE THREAD

**Issue by mattkime** [isobar-idev/isomorphic-react-redux-seed#1] opened 2016-01-26 18:03 UTC
working (or trying to) from a fresh checkout and build. 

```
➜  isomorphic-react-redux-seed git:(master) ✗ npm start

> front-end-tooling-kit@0.0.0 start /Users/mattk/isomorphic-react-redux-seed
> babel-node ./app/bin/www

isomorphic-react-redux-seed/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^

TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/mattk/isomorphic-react-redux-seed/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/Users/mattk/isomorphic-react-redux-seed/node_modules/mongoskin/lib/grid.js:6:35)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mattk/isomorphic-react-redux-seed/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/mattk/isomorphic-react-redux-seed/node_modules/mongoskin/lib/db.js:22:16)
```

i'm uncertain whats causing the error otherwise i'd fix it. do you know?

**Comment by brianfegan** [comment] 2016-01-26 18:06
Have you installed Mongo and inserted the collections from the README?

**Comment by mattkime** [comment] 2016-01-26 18:10
definitely. mongod is running. pardon my n00b, but its my first time with mongo. troubleshooting advice would be much appreciated.

**Comment by brianfegan** [comment] 2016-01-26 18:13
ok, in addition to running mongod, you also need to create a DB called "isomorphic-poc" and then populate it with the categories, and products collections. have you done that?

**Comment by mattkime** [comment] 2016-01-26 18:13
yes

**Comment by brianfegan** [comment] 2016-01-26 18:17
Sorry, just trying to run through all possibilities as I've not seen this error before, and it looks like something install specific as opposed to app specific.

Can you verify mongo is also running at localhost:27017?

**Comment by mattkime** [comment] 2016-01-26 18:26
```
➜  isomorphic-react-redux-seed git:(master) ✗ mongo --port 27017
MongoDB shell version: 3.2.1
connecting to: 127.0.0.1:27017/test
> use isomorphic-poc
switched to db isomorphic-poc
> db
isomorphic-poc
> db.categories.fetch()
2016-01-26T13:24:50.839-0500 E QUERY    [thread1] TypeError: db.categories.fetch is not a function :
@(shell):1:1

> db.categories
isomorphic-poc.categories
> exit
bye
➜  isomorphic-react-redux-seed git:(master) ✗ mongo --port 27017
MongoDB shell version: 3.2.1
connecting to: 127.0.0.1:27017/test
> use isomorphic-poc
switched to db isomorphic-poc
> db.categories.find()
{ "_id" : ObjectId("56a7b1427beee7e93c4bc005"), "id" : 1, "name" : "Best Picture Books" }
{ "_id" : ObjectId("56a7b1427beee7e93c4bc006"), "id" : 2, "name" : "Books (Ages 3-5)" }
> db.products.find()
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc007"), "name" : "Bedtime Math", "price" : 10.79, "image" : "bedtime.jpg", "id" : 17, "categories" : [ 2 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc008"), "name" : "Cowpoke Clyde and Dirty Dawg", "price" : 13.05, "image" : "cowpoke.jpg", "id" : 8, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc009"), "name" : "Daredevil: The Daring Life of Betty Skelton", "price" : 12.23, "image" : "daredevil.jpg", "id" : 13, "categories" : [ 1, 2 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc00a"), "name" : "Exclamation Mark", "price" : 14.11, "image" : "exclamation.jpg", "id" : 7, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc00b"), "name" : "Flora and the Flamingo", "price" : 12.74, "image" : "flora.jpg", "id" : 12, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc00c"), "name" : "Goodnight, Goodnight Construction Site", "price" : 8.1, "image" : "construction.jpg", "id" : 15, "categories" : [ 2 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc00d"), "name" : "If You Want to See a Whale", "price" : 10.56, "image" : "whale.jpg", "id" : 4, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc00e"), "name" : "Oh, the Places You'll Go!", "price" : 11.44, "image" : "places.jpg", "id" : 16, "categories" : [ 2 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc00f"), "name" : "Ol' Mama Squirrel", "price" : 12.84, "image" : "squirrel.jpg", "id" : 11, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc010"), "name" : "Open This Little Book", "price" : 12.9, "image" : "littlebook.jpg", "id" : 10, "categories" : [ 1, 2 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc011"), "name" : "Ribbit!", "price" : 12.05, "image" : "ribbit.jpg", "id" : 5, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc012"), "name" : "Steam Train, Dream Train", "price" : 9.93, "image" : "steam.jpg", "id" : 2, "categories" : [ 1, 2 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc013"), "name" : "That Is Not a Good Idea!", "price" : 12.15, "image" : "notagoodidea.jpg", "id" : 3, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc014"), "name" : "The Day the Crayons Quit", "price" : 10.37, "image" : "crayons.jpg", "id" : 1, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc015"), "name" : "The Going-To-Bed Book", "price" : 5.39, "image" : "goingtobed.jpg", "id" : 18, "categories" : [ 2 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc016"), "name" : "The Matchbox Diary", "price" : 12.92, "image" : "matchbox.jpg", "id" : 9, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc017"), "name" : "The Story of Fish and Snail", "price" : 9.93, "image" : "fishandsnail.jpg", "id" : 6, "categories" : [ 1 ] }
{ "_id" : ObjectId("56a7b14d7beee7e93c4bc018"), "name" : "The Very Hungry Caterpillar", "price" : 16.78, "image" : "caterpillar.jpg", "id" : 14, "categories" : [ 1 ] }
>
```

**Comment by brianfegan** [comment] 2016-01-26 18:29
In /app/app.js try changing line 12...
let db = monk('localhost:27017/isomorphic-poc');
to...
let db = monk('127.0.0.1:27017/isomorphic-poc');

...and let me know what happens.

**Comment by mattkime** [comment] 2016-01-26 21:18
no change. it looks like its bailing before executing any real code in `app/app.js`. I definitely think its getting hung up on module loading. wonder if the npm warnings are the real problem -

```
➜  isomorphic-react-redux-seed git:(master) ✗ npm install
npm WARN EPEERINVALID mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID mongoskin@1.4.13 requires a peer of mongodb@~1.4 but none was installed.
```

**Comment by weblancaster** [comment] 2016-01-26 21:20
@mattkime check de module version (if there's a newer version try install) and try removing `node_modules` folder and then running `npm install` please

**Comment by mattkime** [comment] 2016-01-26 21:44
here we go - 

this relies on monk. monk relies on an older version of mongoskin (v1.4.13) that requires mongodb v1.4

this might not be seen on npm <3

**Comment by brianfegan** [comment] 2016-01-26 22:51
@mattkime, if you clear your node_modules, and update package.json like...
"mongodb": "~1.4"
...and then run npm install...does that fix your issue?

**Comment by piyushbeli** [comment] 2016-08-26 06:33
I had the same issue. I think I had higher version of mongodb installed globally. After putting "mongodb": "~1.4" in package.json, it did not give above error.

**Comment by brianfegan** [comment] 2016-08-29 15:29
Closing issue per confirmed fix from @piyushbeli.

**Closed as completed by brianfegan** 2016-08-29 15:29 UTC
